name: CI on x86_64 macOS

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
 push:
   branches: [ master ]
 workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.php-versions }} on macOS x86_64
    runs-on: macos-latest
    strategy:
      matrix:
        php-versions: [ "8.0", "8.1", "8.2" ]
    steps:
      - uses: actions/checkout@v3

      # Install macOS missing packages and mark os suffix
      - run: |
          brew install automake gzip
          echo "SPC_BUILD_OS=macos" >> $GITHUB_ENV

      # Cache composer dependencies
      - id: cache-composer-deps
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-dependencies

      # If there's no Composer cache, install dependencies
      - if: steps.cache-composer-deps.outputs.cache-hit != 'true'
        run: composer update --no-dev --classmap-authoritative

      # Cache downloaded source
      - id: cache-download
        uses: actions/cache@v3
        with:
          path: downloads
          key: php-${{ matrix.php-versions }}-dependencies

      # If there's no dependencies cache, fetch sources, with or without debug
      - if: steps.cache-download.outputs.cache-hit != 'true'
        run: ./bin/spc download --with-php=${{ matrix.php-versions }} --all

      - name: Remove tmp directory
        run: |
          rm -rf tmp/* && rm -rf buildroot/bin/*
          
      # Run build command
      - run: ./bin/spc build --build-cli --build-micro "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,filter,fileinfo,gd,iconv,mbstring,mbregex,mysqli,mysqlnd,openssl,opcache,pcntl,pdo,pdo_mysql,pdo_sqlite,pdo_pgsql,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib,mongodb,xlswriter,event,shmop" -I "momory_limit=256M"

      - uses: actions/upload-artifact@v3
        with:
          name: php-${{ matrix.php-versions }}-${{ env.SPC_BUILD_OS }}
          path: buildroot/bin/php

      - uses: actions/upload-artifact@v3
        with:
          name: micro-${{ matrix.php-versions }}-${{ env.SPC_BUILD_OS }}
          path: buildroot/bin/micro.sfx

      - name: Pack PHP ${{ matrix.php-versions }} to archive
        run: |
          cd buildroot/bin
          tar -zcvf "php-${{ matrix.php-versions }}-static-bin-macos_x86_64.tar.gz" ./php && rm ./php && mv "php-${{ matrix.php-versions }}-static-bin-macos_x86_64.tar.gz" ../../tmp/
          if [ -f "./micro.sfx" ]; then
            tar -zcvf "micro-${{ matrix.php-versions }}-bin-macos_x86_64.tar.gz" ./micro.sfx && rm ./micro.sfx && mv "micro-${{ matrix.php-versions }}-bin-macos_x86_64.tar.gz" ../../tmp/
          fi
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SERVER_SECRET_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "tmp/"
          REMOTE_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_SERVER_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_SERVER_USER }}
          TARGET: ${{ secrets.DEPLOY_SERVER_TARGET }}
      - name: Deploy
        run: |
          curl ${{ secrets.DEPLOY_URL }}

